{******************************************************************************}
{                             FreeEsVclComponents                              }
{                           ErrorSoft(c) 2015-2016                             }
{                                                                              }
{           errorsoft@mail.ru | vk.com/errorsoft | github.com/errorcalc        }
{     errorsoft@protonmail.ch | habrahabr.ru/user/error1024 | errorsoft.org    }
{                                                                              }
{ Open this on github: github.com/errorcalc/FreeEsVclComponents                }
{                                                                              }
{ ¬ы можете заказать разработку VCL/FMX компонента на заказ                    }
{ You can order the development of VCL/FMX components to order                 }
{******************************************************************************}

// Activate FixLoadPng if you are having problems downloading PNG images in the Design time,
// because of some installed packages (ex: AlphaSkins)
// ---
// јктивируйте FixLoadPng, если у вас возникли проблемы с загрузкой изображений в формате PNG в Design Time,
// из-за некоторых установленных пакетов (к примеру AlphaSkins)

{$define FixLoadPng}