{******************************************************************************}
{                                                                              }
{                       EsVclComponents/EsVclCore v4.4                         }
{                           errorsoft(c) 2009-2023                             }
{                                                                              }
{                     More beautiful things: errorsoft.org                     }
{                                                                              }
{    errorsoft@mail.ru | github.com/errorcalc | habrahabr.ru/user/error1024    }
{          You can write to me in the Telegram messenger: @errorsoft           }
{                                                                              }
{           Star me github: github.com/errorcalc/FreeEsVclComponents           }
{                                                                              }
{                 You can order developing vcl/fmx components,                 }
{               please submit your requests to mail or telegram.               }
{                                                                              }
{******************************************************************************}

// Activate FixLoadPng if you are having problems downloading PNG images in the Design time,
// because of some installed packages (ex: AlphaSkins)
// ---
// Активируйте FixLoadPng, если у вас возникли проблемы с загрузкой изображений в формате PNG в Design Time,
// из-за некоторых установленных пакетов (к примеру AlphaSkins)

{$define FixLoadPng}